### ISSUE TITLE
Error importing python standard function 

### ISSUE THREAD

**Issue by yoavnir** [yoavnir/specs2016#133]
Sometimes but not always, the following in `localfuncs.py` generates an error:
`from math import factorial`

We call the `getargspec` function in `PythonFunctionCollection::Initialize` and this returns NULL for the `factorial` function.

Not sure if this is the reason, but the failing case is using `getargspec` rather than `getfullargspec`.

**Comment by yoavnir** [comment]
Re-compling on centos with Python 3.5m I get to use `getfullargspec`, but still get the same.

So this is not the issue.  Could be a Mac OS vs Linux thing?  Will try on Mint when I get home.

**Comment by yoavnir** [comment]
Re-compiling with 3.8 didn't help, except I got a stranger error: 
`ImportError: /usr/local/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type`

Also to get it to compile, I needed to add `--embed` to `--ldflags`.  But that doesn't work in older versions.  Try both?  Because in 3.8, without the `--embed` I didn't get the `-lpython3.8` linker flag, and `specs` didn't build.

**Comment by yoavnir** [comment]
I find this problem only in the CentOS 7 machine.   Could it be that the issue is really `gcc 4.8.5`

**Comment by FlorianSchwendinger** [comment]
> Re-compiling with 3.8 didn't help, except I got a stranger error:
> `ImportError: /usr/local/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type`
> 
> Also to get it to compile, I needed to add `--embed` to `--ldflags`. But that doesn't work in older versions. Try both? Because in 3.8, without the `--embed` I didn't get the `-lpython3.8` linker flag, and `specs` didn't build.

I had the same issue on fedora 32. Since Python3 the shared library is called e.g. `libpython3.7m.so` in fedora 32 it is called `libpython3.8.so`. So in my case the issue was my program did try to load a non existing shared library (`libpython3.8m.so`). It could be the case that you face the same problem at CentOS7.

**Comment by yoavnir** [comment]
On CentOS7 I couldn't find any python 3.8 shared library. 

But the other functions in my localfuncs.py file are loading and some are using floating point types, and so is the specs function itself.  It also works fine on my other Linux machine.  Pretty curious.
