### ISSUE TITLE
make some:  error: ‘isnan’ was not declared in this scope

### ISSUE THREAD

**Issue by ok6245** [yoavnir/specs2016#55]
Ubuntu 16.04
$ g++ -v
...
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

Steps I used:
Feb 5, 2019 
git clone https://github.com/yoavnir/specs2016.git
git checkout stable

I tried to build the executable:
cd to src directory

$ make some
g++  -Werror -O3 -DGITTAG=v0.2 --std=c++11 -I .  -c -o utils/alu.o utils/alu.cc
utils/alu.cc: In member function ‘void ALUValue::set(ALUFloat)’:
utils/alu.cc:49:13: error: ‘isnan’ was not declared in this scope
  if (isnan(f)) {
             ^
utils/alu.cc:49:13: note: suggested alternative:
In file included from utils/alu.cc:11:0:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
<builtin>: recipe for target 'utils/alu.o' failed
make: *** [utils/alu.o] Error 1
$

After following the suggestion in the error output (and at this link https://stackoverflow.com/questions/39130040/cmath-hides-isnan-in-math-h-in-c14-c11), I updated utils/alu.cc, line 48 from:
   if (isnan(f)) {
to
  if (std::isnan(f)) {

Now the make is successful. 

I saw a reference in issue #14 Support  Windows about isnan() being not found also. Is this the same problem?

**Comment by yoavnir** [comment]
Thanks!

> I saw a reference in issue #14 Support Windows about isnan() being not found also. Is this the same problem?

Very likely. I'm writing this on a Mac and compiling also an a Linux box, but that has an older gcc (4.8.something or 4.9.something).

**Comment by yoavnir** [comment]
Comitted to dev:
```
commit 1513d47da7d2f2a7982338190de33e4c463fb6cc (HEAD -> dev, github/dev)
Author: synp71 <yoav.nir@gmail.com>
Date:   Wed Feb 6 06:33:47 2019 +0200

    Issue #55: Use std::isnan() instead of isnan() for compatibility
    
    Signed-off-by: synp71 <yoav.nir@gmail.com>
```

**Comment by yoavnir** [comment]
Cherry-picked and committed to `stable`:
```
commit 96035865b10440611bcbddf1c76d53e4d75bf6f5 (HEAD -> stable, github/stable)
Author: synp71 <yoav.nir@gmail.com>
Date:   Wed Feb 6 06:33:47 2019 +0200

    Issue #55: Use std::isnan() instead of isnan() for compatibility
    
    Signed-off-by: synp71 <yoav.nir@gmail.com>
```

**Comment by yoavnir** [comment]
Updated the `v0.2` tag.

Thanks!
